<a href="https://colab.research.google.com/github/Sheba-Ayinzabyonna/Assignment/blob/master/Numpy_Tutorial_For_AI_Discussion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Python libraries play a crucial role in machine learning by providing a wide range of tools and functionalities that simplify the development, implementation, and deployment of machine learning models. 
The most popular of these libraries are;
- Numpy
- Pandas
- Matplotlib
- Sci-kit learn
- Seaborn ... to mention but a few

Today we'll going through an Numpy.
NB: This isn't an exhaustive tutorial on Numpy, just enough get you to know the basics and the most common aplications in Machine Learning.

Compiled by KikuleShawnJ

##WHAT IS NUMPY

Numpy(Numerical Python) is a Python library for creating and manipulating matrices, the main data structure used by Machine Learning algorithms. Matrices are mathematical objects used to store values in rows and columns.

Python calls matrices lists, NumPy calls them arrays and TensorFlow calls them tensors. Python represents matrices with the list data type.

It provides efficient N-dimensional array objects, mathematical functions, linear algebra operations, and random number generation. NumPy is the backbone of many other libraries in the scientific computing and machine learning ecosystem.


##IMPORT NumPy MODULE

Run the code cells below to import NumPy and check the version.


In [2]:
#installing numpy
!pip install numpy



Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [3]:
import numpy as np

In [4]:
np.__version__

'1.22.4'

##POPULATING NUMPY ARRAYS SPECIFIC NUMBERS
We use `np.array` to create numpy arrays with your own values.
You can specify the datatype using `dtype` argument(The default is int64).
The code cell below creates a 5 element array, whose elements are of type 'float32':

In [5]:
one_dimensional_array=np.array([1,2,3,4,5])
print(one_dimensional_array)

[1 2 3 4 5]


In [7]:
#can change the data type to floats
one_dimensional_array=np.array([1,2,3,4,5], dtype='float32')
print(one_dimensional_array)

[1. 2. 3. 4. 5.]


In [8]:
two_dimensional_array=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(two_dimensional_array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [26]:
three_dimensional_array=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(three_dimensional_array)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


You can also create a two dimensional array in the same way, just by adding a layer of square brackets. The code cell below creates a 3x2 numpy array.

You can also populate populate a numpy array specifically with zero's and one's

In [9]:
print(np.zeros(5))
print(np.ones(5))

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]


## POPULATING NUMPY ARRAYS WITH A SEQUENCE OF NUMBERS
You can populate the arrays with a sequence of numbers from a specific lower bound, to a specific upper bound

In [12]:
#5 lower bound is included
#11 upper bound not included
sequence_integers=np.arange(5,11)
print(sequence_integers)

[ 5  6  7  8  9 10]


In [14]:
#skip 2 = size
sequence_two=np.arange(0,11,2)
print(sequence_two)

[ 0  2  4  6  8 10]


##POPULATING NUMPY ARRAYS WITH RANDOM NUMBERS
NumPy provides many functions to populate arrays with random numbers across certain ranges. For example, `np.random.randint` generates random integers between a low and high value. The following call populates a 5-element array with random integers between 1 and 50. 

In [16]:
random_array=np.random.randint(low=1, high=51, size=(5))
print(random_array)

[23 44 40 35 43]


You can also create an array of random floating point numbers using `np.random.random` between 0 and 1.

In [17]:
random_2=np.random.random(5)
print(random_2)

[0.65497973 0.44929936 0.43987657 0.0840961  0.54042583]


In [18]:
random_3=np.random.uniform(1,51, size=5)
print(random_3)

[37.75011205 42.93420468 29.36976681 24.6019747  32.00965273]


##MATHEMATICAL OPERATIONS ON NUMPY OPERANDS
NumPy uses a technique called broadcasting to simplfy addition, subtraction and multiplication of NumPy operands as illustrated in the code cell below.

In [19]:
broad=np.random.randint(20,31, 10)
print(broad)

[26 24 21 23 21 20 29 24 21 20]


In [20]:
#addition
print(broad+2)

[28 26 23 25 23 22 31 26 23 22]


In [21]:
#subtraction
print(broad-2)

[24 22 19 21 19 18 27 22 19 18]


In [22]:
#multiplication
print(broad*2)

[52 48 42 46 42 40 58 48 42 40]


##TASK 1
Create a simple dataset consisting of a simple feature and label as follows:
1. Assign a sequence of integers from 5 to 20(inclusive) to a NumPy array named `feature`.
2. Assign 15 values to a NumPy array named `label`, such that:
```
label = (2)feature + 4
```
for example, the first value in label should be;
```
label (2)(5) + 4 = 14
```

In [24]:
#1
feature= np.arange(5,21)
print(feature)

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [25]:
#2
label=feature*2
label=label+4
print(label)

[14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44]


##TASK 2
Randomize your dataset by adding different random floating point numbers between -4 and 4 to the `label` dataset.

Hint : Do not rely on broadcasting, create a different array with the same dimensions as the label array then add the two.

In [29]:
random =np.random.uniform(-4,4, size=16)
print(random.dtype)

float64


##ARRAY INDEXING
You can access elements of an array using their index numbers. Indices start from 0, and the second index has 1, and so on.

ACCESSING 2D ARRAYS

To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.



ACCESSING 3D ARRAYS

To access elements from 3D arrays is similar

##ARRAY SLICING
Slicing in python is simply taking elements from one given index to another given index.
`[start:end]`
or
`[start:end:step]`
If we don't specify a start, it is considered zero.
If we don't specify an end, its considered the remaining length of the array in that dimension.
The default step is 1.